"""fix_expenses_schema

Revision ID: 0731b6445e36
Revises: c1ccb05706bf
Create Date: 2026-02-05 02:17:02.889613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0731b6445e36'
down_revision: Union[str, None] = 'c1ccb05706bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_type',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   nullable=False,
                   existing_server_default=sa.text("'INDIRECT'"))
        batch_op.create_foreign_key('fk_expenses_crop', 'crops', ['crop_id'], ['crop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'INDIRECT'"))
    # ### end Alembic commands ###
