"""add_session_model_and_created_by_fields

Revision ID: 8b26e5fcfc4f
Revises: f85bee693364
Create Date: 2025-12-19 22:46:36.230066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b26e5fcfc4f'
down_revision: Union[str, None] = 'f85bee693364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Sessions table
    op.create_table('sessions',
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_token', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('last_activity', sa.DateTime(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)

    # Add columns to existing tables (without FK constraints to avoid SQLite issues)
    op.add_column('expenses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.create_foreign_key(None, 'expenses', 'users', ['created_by'], ['user_id'])
    
    op.add_column('general_ledger', sa.Column('created_by', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'general_ledger', 'users', ['created_by'], ['user_id'])
    
    op.add_column('payments', sa.Column('created_by', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'payments', 'users', ['created_by'], ['user_id'])
    
    op.add_column('purchases', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.create_foreign_key(None, 'purchases', 'users', ['created_by'], ['user_id'])
    
    op.add_column('sales', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('created_at', sa.DateTime(), nullable=True))
    # op.create_foreign_key(None, 'sales', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'created_at')
    op.drop_column('sales', 'created_by')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'created_at')
    op.drop_column('purchases', 'created_by')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'created_by')
    op.drop_constraint(None, 'general_ledger', type_='foreignkey')
    op.drop_column('general_ledger', 'created_by')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'created_by')
    # ### end Alembic commands ###
